//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 10:48:06 AM GMT 
//


package it.eng.de4idsa.datex2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for _ImpactExtensionType is adapted Engineering FIX.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_ImpactExtensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="impactDetails" type="{http://datex2.eu/schema/2/2_0}ImpactDetails" minOccurs="0"/>
 *         &lt;element name="impactExtended" type="{Engineering Fix} ImpactExtended" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_ImpactExtensionType", propOrder = {
    "impactDetails",
    "impactExtended"
})
public class ImpactExtensionType {

    protected ImpactDetails impactDetails;
    protected ImpactExtended impactExtended;

    /**
     * Gets the value of the impactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ImpactDetails }
     *     
     */
    public ImpactDetails getImpactDetails() {
        return impactDetails;
    }

    /**
     * Sets the value of the impactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpactDetails }
     *     
     */
    public void setImpactDetails(ImpactDetails value) {
        this.impactDetails = value;
    }

    /**
     * Gets the value of the impactExtended property.
     * 
     * @return
     *     possible object is
     *     {@link ImpactExtended }
     *     
     */
    public ImpactExtended getImpactExtended() {
		return impactExtended;
	}

    /**
     * Sets the value of the impactExtended property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpactExtended }
     *     
     */
	public void setImpactExtended(ImpactExtended impactExtended) {
		this.impactExtended = impactExtended;
	}
    
}
